---
- name: install apache webserver
  remote_user: admin
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: "Install apache2"
      apt: 
        name: apache2 
        state: present

    - name: Enable mod rewrite
      apache2_module: 
        name: rewrite 
        state: present
      
    - name: Enable the use of .htaccess file in the project. 
      copy: 
       src: enable_htaccess.conf
       dest: /etc/apache2/sites-available/enable_htaccess.conf
     
    - name: "Restart Apache"
      service: 
        name: apache2 
        state: restarted
