---
- name: Install PHP 7
  remote_user: admin
  hosts: all
  become: true
  become_user: root
  gather_facts: true
  tasks:
    - name: Add ondrej repository for later versions of PHP.
      apt_repository: repo='ppa:ondrej/php' update_cache=yes

    - name: "Install PHP 7 and other dependencies."
      apt: 
        state: present
        name: 
          - acl
          - git 
          - curl
          - unzip
          - sendmail
          - php7.4-common
          - php7.4-cli
          - php7.4-dev
          - php7.4-gd
          - php7.4-curl
          - php7.4-zip
          - php7.4-json
          - php7.4-opcache
          - php7.4-tidy
          - php7.4-mcrypt
          - php7.4-xml
          - php7.4-xmlrpc
          - php7.4-mbstring
          - php7.4-pdo
          - php7.4-mysql
          - php-apcu
          - libpcre3-dev
          - libapache2-mod-php7.4
         
