---
- name: Install WordPress with LAMP Stack.
  hosts: all
  remote_user: admin
  become: true
  become_user: root
  gather_facts: true

  pre_tasks:
   - name: Update apt cache if needed.
     apt: update_cache=yes cache_valid_time=3600

  tasks:
   - name: Get software for apt repository management.
     apt:
       state: present
       name:
         - python3-apt
         - python3-pycurl

   - name: Ensure pip3 is installed on the Server node(s).
     apt: 
       name: python3-pip
       cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
       install_recommends: no
       state: latest
       update_cache: yes

  tags: 
    - pip

- name: Include Apache
  import_playbook: apache.yml

- name: Include PHP
  import_playbook: php.yml

- name: Include MySQL
  import_playbook: mysql.yml

- name: Include WordPress
  import_playbook: wordpress.yml
